//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceIssueApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurerDetail
    {
        public long InsurerId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public int MobileNo { get; set; }
        public int State { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public int Gender { get; set; }
        public int AgentId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public long TempPolicyNo { get; set; }
    
        public virtual PolicyNoGeneration PolicyNoGeneration { get; set; }
    }
}
