//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceIssueApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineeDetail
    {
        public long NomineeId { get; set; }
        public long TempPolicyNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
    
        public virtual PolicyNoGeneration PolicyNoGeneration { get; set; }
    }
}
