//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceIssueApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public long InsurerPersonalId { get; set; }
        public long TempPolicyNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string PersonalOccupation { get; set; }
        public Nullable<long> AadharNo { get; set; }
        public string PanNo { get; set; }
    }
}
