//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceIssueApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDetail
    {
        public long Id { get; set; }
        public long TempPolicyNo { get; set; }
        public long SumAssured { get; set; }
        public Nullable<int> PolicyTerm { get; set; }
        public Nullable<int> SmokerStatus { get; set; }
        public Nullable<System.DateTime> PolicyCreatedDate { get; set; }
        public Nullable<System.DateTime> NextPremiumDueDate { get; set; }
    
        public virtual PolicyNoGeneration PolicyNoGeneration { get; set; }
    }
}
