//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceIssueApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyNoGeneration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyNoGeneration()
        {
            this.InsurerDetails = new HashSet<InsurerDetail>();
            this.MedicalDetails = new HashSet<MedicalDetail>();
            this.NomineeDetails = new HashSet<NomineeDetail>();
            this.PolicyDetails = new HashSet<PolicyDetail>();
        }
    
        public long TempPolicyNo { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<int> PolicyStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurerDetail> InsurerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalDetail> MedicalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NomineeDetail> NomineeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyDetail> PolicyDetails { get; set; }
    }
}
